import { headerLink, headerLinkUa } from '../Data/component';

export const dictionaryEnglish = {
  headerLink: headerLink,
  myName: 'Dmitry Moskalenko',
  contact: 'Contact',
  preview:
    "Hi there, I'm a Ukraine based Front-End Developer focused on crafting clean && user friendly experiences.",
  aboutBtn: 'About me',
  skill: 'My skills',
  more: 'Click for more',
  disignedBy: 'Designed by',
  summaryTitle: 'Summary',
  summary: `I'm passionate junior front-end developer with a desire to learn and grow in a collaborative team environment.
  Seeking for new opportunities and challenges that will expand my skill set and complement your company with a motivated specialist.  I have commercial (3 months) and non-commercial experience in creating websites. Technologies used:
  React, Firebase, NodeJS, PostgreSQL etc.`,
  myGit: 'And other in my profile on GitHub :',
  educationTitle: 'Education',
  university: 'National Technical University Dnipro Polytechnic',
  degree: `2015-2019 Bachelor Degree Field of study Mining. Professional qualification "Specialist in the field of mining"`,
  additionalEducation: 'Additional Education',
  basicCourse:
    'Basic Course - Front End Basic (HTML/CSS/SCSS) 08.2021 - 11.2021',
  advancedCourse: `In-depth course - Front End Pro (Advanced). JavaScript + React 12.2021 -
  06.2022`,
  udemyFirst: 'Udemy: JavaScript + React (Ivan Petrichenko)',
  udemySecond: 'Udemy: React + Redux (Juriy Bura)',
  udemyThirdL: 'Udemy: Understanding TypeScript (Maximilian Schwarzmuller)',
  additionalInfo: 'Additional information',
  language: 'English - Pre-Intermediate (A2)',
  experienceTitle: 'Work Experience',
  frontPosition: 'Junior Front-End Developer',
  frontFreelance: `Freelance with coach
  September 2022 - December 2022`,
  collaborated: `Collaborated with the coach to design new features for web application.`,
  createdMap: `Created an interactive map and chat for clients. Stack React / Typescript / Redux-Toolkit / Firebase / Mapbox.`,
  maintance: `Maintenance of code, debugging and solving client/server side problems `,
  positionAllo: `Company LLC 'ALLO'
  03.2019 - 02.2022`,
  position: 'Sales expert / Acting director',
  goodsSales: 'Sale of non-food products',
  interview: 'Interview of new employees',
  otherWork:
    'Work with goods, cash registers, deliveries, processing of documents, invoices, etc',
  softSkillTitle: 'Soft Skills',
  adaptability: 'Adaptability',
  resultOriented: 'Result oriented',
  teamworker: 'Teamworker',
  communication: 'Communication',
  basicCertificate: 'Front End Basic (Certificate)',
  advancedCertificate: 'Front End Advanced (Certificate)',
  traineeCertificate: 'Trainee Evo Fintech (Fintech Product in Ukraine)',
  portfolioLink: 'Link',
  crudContacts: 'CRUD Contacts (React-Redux / Redux-Thunk / Formik(Yup) etc..)',
  analytics: 'Analytics Website (1 page) HTML/SCSS/JavaScript',
  reactTodo: 'CRUD To do List with MockApi (React / React Hooks)',
  jsTodo: 'CRUD Todo List with MockApi (JavaScript)',
  clock: 'Clock and Stopwatch (JavaScript)',
  weather: 'Weather App (Api openWeather) JavaScript',
  myPortfolio: 'Portfolio (ReactJs/Hooks/Router/ModuleCSS) + Webpack/Babel',
  rickMorty: 'Rick and Morty Fan Page (React/Redux)',
  uichat: 'UI Chat (React/Redux/WebSocket)',
  home: 'Home',
  about: 'About',
  portfolio: 'Portfolio',
  jWallet: 'Wallet App (Task on the position Trainee/Junior)',
  jStore: 'Mini Store',
  jWalletServer: 'Wallet App + (NodeJs + PostgreSQL)',
  rnmFan: 'Rick and Morty (React + TypeScript /RTK-Query etc)',
  honey: 'Own website. HoneyParadise (React/NodeJS/PostgreSQL etc)',
  lang4u: 'Lang4U Online course. (MERN + TS)',
};

export const dictionaryUkrainian = {
  headerLink: headerLinkUa,
  myName: 'Москаленко Дмитро',
  preview:
    'Привіт, я український фронтенд-розробник, який зосереджується на створенні чистих && зручних для користувачів інтерфейсів.',
  aboutBtn: 'Про мене',
  contact: 'Контакти',
  skill: 'Мої навички',
  more: 'Детальніше',
  disignedBy: 'Розроблено:',
  summaryTitle: 'Резюме',
  summary: `Я запальний молодший фронт-енд розробник з бажанням навчатися та розвиватися в середовищі спільної команди. Шукаю нові можливості та виклики, які розширять мій набір навичок і доповнять вашу компанію мотивованим спеціалістом.
  Маю комерційний (3 місяці) та некомерційний досвід створення сайтів. Використовую технології:
  React, Firebase, NodeJS, PostgreSQL тощо.`,
  myGit: 'Та інші в моєму профілі на GitHub:',
  educationTitle: 'Освіта',
  university: 'Національний технінчий університет "Дніпровська політехніка" ',
  degree:
    '2015 - 2019 Ступінь вищої освіти Бакалавр напрям підготовки Гірництво. Професійна кваліфікація "Фахівець в галузі гірництва"',
  additionalEducation: 'Додаткова освіта',
  basicCourse:
    'Базовий курс - Front End Basic (HTML/CSS/SCSS) 08.2021 - 11.2021',
  advancedCourse: `Просунутий курс - Front End Pro (Advanced). JavaScript + React 12.2021 -
    06.2022`,
  udemyFirst: 'Udemy: JavaScript + React (Іван Петриченко)',
  udemySecond: 'Udemy: React + Redux (Юрій Бура)',
  udemyThirdL: 'Udemy: Understanding TypeScript (Максиміліан Шварцмюллер)',
  additionalInfo: 'Додаткова інформація',
  language: 'Англійська нижче середнього (A2)',
  experienceTitle: 'Досвід роботи',

  frontPosition: 'Junior Front-End Developer',
  frontFreelance: `Фріланс з викладачем Вересень 2022 - Грудень 2022`,
  collaborated: `Співпрацював із тренером для розробки нових функцій для веб-додатків.`,
  createdMap: `Створив інтерактивну карту та чат для клієнтів. Технологічний стек React / Typescript / Redux-Toolkit / Firebase / Mapbox.`,
  maintance: `Обслуговування коду, налагодження та вирішення проблем на стороні клієнт/сервер`,

  positionAllo: 'ТОВ Алло 03.2019 - 02.2022',
  position: 'Експерт з продажу / ВО Директора',
  goodsSales: 'Продаж непродовольчих товарів',
  interview: 'Співбесіда нових співробітників',
  otherWork:
    'Робота з товарами, касовими апаратами, поставками, оформлення документів, рахунки-фактури тощо',
  softSkillTitle: "М'які навички",
  adaptability: 'Адаптивність',
  resultOriented: 'Орієнтований на результат',
  teamworker: 'Командний працівник',
  communication: 'Спілкування',
  basicCertificate: 'Front End Базовий (Сертифікат)',
  advancedCertificate: 'Front End Просунутий (Сертифікат)',
  traineeCertificate: 'Trainee Evo Fintech (Фінтех продукти в Україні)',
  portfolioLink: 'Посилання',
  crudContacts:
    'Контакти (CRUD - React-Redux / Redux-Thunk / Formik (Yup) тощо)',
  analytics: 'Аналітичний веб-сайт (1 сторінка) HTML/SCSS/JavaScript',
  reactTodo: 'CRUD Список справ за допомогою MockApi (React/React Hooks)',
  jsTodo: 'CRUD Список справ за допомогою MockApi (JavaScript)',
  clock: 'Годинник і секундомір (JavaScript)',
  weather: 'Програма погоди (Api openWeather) JavaScript',
  myPortfolio: 'Портфоліо (ReactJs/Hooks/Router/ModuleCSS) + Webpack/Babel',
  rickMorty: 'Фан сторінка Рік та Морті (React/Redux)',
  uichat: 'Чат (React/Redux/WebSocket)',
  home: 'Головна',
  about: 'Про мене',
  portfolio: 'Портфоліо',
  jWallet: 'Гаманець (завдання на позицію Trainee/Junior)',
  jStore: 'Міні магазин',
  jWalletServer: 'Гаманець повна версія (NodeJs, PostgreSQL)',
  rnmFan: 'Фан сторінка Рік та Морті (React + TypeScript /RTK-Query etc)',
  honey: 'Медовий рай. Власний сайт (React/NodeJS/PostgreSQL)',
  lang4u: 'Lang4U курси іноземних мов (MERN + TS)',
};
