import { headerLink, headerLinkUa } from '../Data/component';

export const dictionaryEnglish = {
  headerLink: headerLink,
  myName: 'Dmitry Moskalenko',
  contact: 'Contact',
  preview:
    "Hi there, I'm a Ukraine based front end developer (JavaScript/React) focused on crafting clean && user friendly experiences.",
  aboutBtn: 'About me',
  skill: 'My skills',
  more: 'Click for more',
  disignedBy: 'Designed by',
  summaryTitle: 'Summary',
  summary: `I'm looking for a full-time/part-time or remote job as a Trainee/Junior
  Front End Developer. I have non-commercial experience in creating
  websites. Technologies used: HTML, CSS(SCSS), JavaScript, React (React - Redux/RTK/RTK Query), TypeScript,
  NodeJs/Fastify. I would like to invite you to review some projects in
  my portfolio:`,
  myGit: 'And other in my profile on GitHub :',
  educationTitle: 'Education',
  university: 'National Technical University Dnipro Polytechnic',
  degree: `2015-2019 Bachelor Degree Field of study Mining. Professional qualification "Specialist in the field of mining"`,
  additionalEducation: 'Additional Education',
  basicCourse:
    'Basic Course - Front End Basic (HTML/CSS/SCSS) 08.2021 - 11.2021',
  advancedCourse: `In-depth course - Front End Pro (Advanced). JavaScript + React 12.2021 -
  06.2022`,
  udemyFirst: 'Udemy: JavaScript + React (Ivan Petrichenko)',
  udemySecond: 'Udemy: React + Redux (Juriy Bura)',
  udemyThirdL: 'Udemy: Understanding TypeScript (Maximilian Schwarzmuller)',
  additionalInfo: 'Additional information',
  language: 'English - Pre-Intermediate (A2)',
  experienceTitle: 'Work Experience',
  position: 'Sales expert / Acting director',
  goodsSales: 'Sale of non-food products',
  interview: 'Interview of new employees',
  otherWork:
    'Work with goods, cash registers, deliveries, processing of documents, invoices, etc',
  softSkillTitle: 'Soft Skills',
  adaptability: 'Adaptability',
  resultOriented: 'Result oriented',
  teamworker: 'Teamworker',
  basicCertificate: 'Front End Basic (Certificate)',
  advancedCertificate: 'Front End Advanced (Certificate)',
  traineeCertificate: 'Trainee Evo Fintech (Fintech Product in Ukraine)',
  portfolioLink: 'Link',
  crudContacts: 'CRUD Contacts (React-Redux / Redux-Thunk / Formik(Yup) etc..)',
  analytics: 'Analytics Website (1 page) HTML/SCSS/JavaScript',
  reactTodo: 'CRUD To do List with MockApi (React / React Hooks)',
  jsTodo: 'CRUD Todo List with MockApi (JavaScript)',
  clock: 'Clock and Stopwatch (JavaScript)',
  weather: 'Weather App (Api openWeather) JavaScript',
  myPortfolio: 'Portfolio (ReactJs/Hooks/Router/ModuleCSS) + Webpack/Babel',
  rickMorty: 'Rick and Morty Fan Page (React/Redux)',
  uichat: 'UI Chat (React/Redux/WebSocket)',
  home: 'Home',
  about: 'About',
  portfolio: 'Portfolio',
  jWallet: 'Wallet App (Task on the position Trainee/Junior)',
  jStore: 'Mini Store',
  jWalletServer: 'Wallet App + (NodeJs + PostgreSQL)',
  rnmFan: 'Rick and Morty (React + TypeScript /RTK-Query etc)',
  honey: 'Own website. HoneyParadise (React/NodeJS/PostgreSQL etc)',
  lang4u: 'Lang4U Online course. (MERN + TS)',
};

export const dictionaryUkrainian = {
  headerLink: headerLinkUa,
  myName: 'Москаленко Дмитро',
  preview:
    'Привіт, я український фронтенд-розробник (JavaScript/React), який зосереджується на створенні чистих && зручних для користувачів інтерфейсів.',
  aboutBtn: 'Про мене',
  contact: 'Контакти',
  skill: 'Мої навички',
  more: 'Детальніше',
  disignedBy: 'Розроблено:',
  summaryTitle: 'Резюме',
  summary: `Шукаю повну/неповну зайнятість або віддалену роботу в якості Trainee/Junior
  Front End розробника. Маю некомерційний досвід створення
  веб-сторінок. Використовую технології: HTML, CSS(SCSS), JavaScript, React (React-Redux/RTK/RTK Query), TypeScript,
  NodeJs/Fastify. Я хотів би запросити вас переглянути деякі проєкти в
  моєму портфоліо:`,
  myGit: 'Та інші в моєму профілі на GitHub:',
  educationTitle: 'Освіта',
  university: 'Національний технінчий університет "Дніпровська політехніка" ',
  degree:
    '2015 - 2019 Ступінь вищої освіти Бакалавр напрям підготовки Гірництво. Професійна кваліфікація "Фахівець в галузі гірництва"',
  additionalEducation: 'Додаткова освіта',
  basicCourse:
    'Базовий курс - Front End Basic (HTML/CSS/SCSS) 08.2021 - 11.2021',
  advancedCourse: `Просунутий курс - Front End Pro (Advanced). JavaScript + React 12.2021 -
    06.2022`,
  udemyFirst: 'Udemy: JavaScript + React (Іван Петриченко)',
  udemySecond: 'Udemy: React + Redux (Юрій Бура)',
  udemyThirdL: 'Udemy: Understanding TypeScript (Максиміліан Шварцмюллер)',
  additionalInfo: 'Додаткова інформація',
  language: 'Англійська нижче середнього (A2)',
  experienceTitle: 'Досвід роботи',
  position: 'Експерт з продажу / ВО Директора',
  goodsSales: 'Продаж непродовольчих товарів',
  interview: 'Співбесіда нових співробітників',
  otherWork:
    'Робота з товарами, касовими апаратами, поставками, оформлення документів, рахунки-фактури тощо',
  softSkillTitle: "М'які навички",
  adaptability: 'Адаптивність',
  resultOriented: 'Орієнтований на результат',
  teamworker: 'Командний працівник',
  basicCertificate: 'Front End Базовий (Сертифікат)',
  advancedCertificate: 'Front End Просунутий (Сертифікат)',
  traineeCertificate: 'Trainee Evo Fintech (Фінтех продукти в Україні)',
  portfolioLink: 'Посилання',
  crudContacts:
    'Контакти (CRUD - React-Redux / Redux-Thunk / Formik (Yup) тощо)',
  analytics: 'Аналітичний веб-сайт (1 сторінка) HTML/SCSS/JavaScript',
  reactTodo: 'CRUD Список справ за допомогою MockApi (React/React Hooks)',
  jsTodo: 'CRUD Список справ за допомогою MockApi (JavaScript)',
  clock: 'Годинник і секундомір (JavaScript)',
  weather: 'Програма погоди (Api openWeather) JavaScript',
  myPortfolio: 'Портфоліо (ReactJs/Hooks/Router/ModuleCSS) + Webpack/Babel',
  rickMorty: 'Фан сторінка Рік та Морті (React/Redux)',
  uichat: 'Чат (React/Redux/WebSocket)',
  home: 'Головна',
  about: 'Про мене',
  portfolio: 'Портфоліо',
  jWallet: 'Гаманець (завдання на позицію Trainee/Junior)',
  jStore: 'Міні магазин',
  jWalletServer: 'Гаманець повна версія (NodeJs, PostgreSQL)',
  rnmFan: 'Фан сторінка Рік та Морті (React + TypeScript /RTK-Query etc)',
  honey: 'Медовий рай. Власний сайт (React/NodeJS/PostgreSQL)',
  lang4u: 'Lang4U курси іноземних мов (MERN + TS)',
};
